### ISSUE TITLE
misleading overview documentation

### ISSUE THREAD

**Issue by g--** [oanda/apidocs#12]
Found a few problems with the documentation
- docs say "/v1/instruments/:instrument/candle" when it's actually "/v1/instruments/:instrument/candles"
- POST "/v1/users/:username" doesn't do anything.  (actually post "/v1/users"?).  It probably should be "PUT" "/v1/users/:username" since you know the resource name ahead of time, or POST "/v1/users"

I was frustrated /v1/instruments/price wasn't working, but I didn't realize it needed a parameter and I could "drill down" on the overview for more details.

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
