### ISSUE TITLE
please add 'id' field to v1/instruments

### ISSUE THREAD

**Issue by ghost** [oanda/apidocs#14]
1 EUR/USD
2 EUR/GBP
3 EUR/JPY
4 EUR/CHF
5 USD/JPY
6 USD/CHF
7 USD/CAD
8 GBP/USD
9 GBP/JPY
10 GBP/CHF
11 AUD/USD
12 AUD/CZK
13 AUD/DKK
14 AUD/HKD
15 AUD/HUF
16 AUD/JPY
17 AUD/MXN
18 AUD/NOK
19 AUD/NZD
20 AUD/PLN

... and etc.

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
