### ISSUE TITLE
"nav" value missing from account details responses

### ISSUE THREAD

**Issue by ccbcraig** [oanda/apidocs#16]
Despite being documented the "nav" value is currently missing from server responses:

GET /v1/accounts/8139117

{
    "accountId" : 8139117,
    "accountName" : "Primary",
    "balance" : 100000,
    "unrealizedPl" : 0,
    "realizedPl" : 0,
    "marginUsed" : 0,
    "marginAvail" : 100000,
    "openTrades" : 0,
    "openOrders" : 0,
    "marginRate" : 0.05,
    "homecurr" : "GBP"
} 

Also, shouldn't "homecurr" be "homeCurr"?

**Comment by ghost** [comment]
no need for extra field.

nav = balance + unrealizedPl

**Comment by ccbcraig** [comment]
Agreed, but then it should be removed from the documentation.

**Comment by ccbcraig** [comment]
Especially since nav != balance + unrealizedPl in the example given!

**Comment by ghost** [comment]
nav field has been removed from the documentation.

commit https://github.com/oanda/apidocs/commit/c6a5962ca17c44800ad9d7c16f95e5f2ab816a05

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
