### ISSUE TITLE
missing fields in response to trade request

### ISSUE THREAD

**Issue by Panurgo** [oanda/apidocs#17]
Hello,

this is the server response to a trade (POST /v1/accounts/:account_id/trades):

{
    "ids" : [
        178471630
    ],
    "instrument" : "EUR_USD",
    "units" : 654127,
    "price" : 1.31661,
    "marginUsed" : 43061.5075,
    "direction" : "short"
}

The following fields are missing:

"time" : ,  
"takeProfit" : ,
"stopLoss" : ,
"trailingStop" : ,

thanks

**Comment by ccbcraig** [comment]
I don't think it is meant to return the trade details.

You can retrieve the trade details using the highest numbered id in the array returned (sometimes there
is more than one id):

GET /v1/accounts/:account_id/trades/:trade_id

**Comment by Panurgo** [comment]
Understand. However those fields are in the documentation here: https://github.com/oanda/apidocs/blob/master/sections/trades.md

Also, i think, the response to a trade should at least contain "time:".

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
