### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by ccbcraig** [oanda/apidocs#19]
GET /v1/accounts/:account_id/orders
GET /v1/accounts/:account_id/trades
GET /v1/accounts/:account_id/transactions

Each of these is currently including "nextPage" even when there are no further items to retrieve. "nextPage" is only omitted from a response with zero items

This results in having to do a redundant query to get a final page with no items.

**Comment by ccbcraig** [comment]
Same problem area - here is an example:

GET /v1/accounts/1499353/transactions?transIds=178549273

{
    "transactions" : [
        {
            "id" : 178549273,
            "accountId" : 1499353,
            "type" : "ChangeOrder",
            "instrument" : "EUR_USD",
            "units" : 100000,
            "time" : "2013-03-01T10:05:18Z",
            "price" : 1.30918,
            "balance" : 100000,
            "profitLoss" : 0,
            "stopLoss" : 1.30526,
            "takeProfit" : 1.31573,
            "expiry" : "2013-03-01T12:05:12Z",
            "completionCode" : 100,
            "transactionLink" : 178549272,
            "marginUsed" : 0
        }
    ],
    "nextPage" : "http:\/\/api-sandbox.oanda.com\/v1\/accounts\/1499353\/transactions?maxTransId=178549272"
}

This "nextPage" then retrieves all transactions prior to the one requested!

And why all the backslashes?

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
