### ISSUE TITLE
Transaction history returns only the latest 50 records. Count and maxTransId params have no effect.

### ISSUE THREAD

**Issue by cloudspider** [oanda/apidocs#20]
http://api-sandbox.oanda.com/v1/accounts/5172550/transactions?count=100

Returns only the most recent 50 transaction records.
Paging has no effect, once the latest 50 transactions are returned.

http://api-sandbox.oanda.com/v1/accounts/5172550/transactions?count=40&maxTransId=178692345

**Comment by aianus** [comment]
Thanks for bringing this to our attention. Should be fixed now.
