### ISSUE TITLE
v1/instruments does not return all symbols that are available within the platform

### ISSUE THREAD

**Issue by ghost** [oanda/apidocs#21]
Full list here: https://github.com/laurinkus/oanda-java-api/blob/master/SymbolStore/symbols.txt

**Comment by cyip** [comment]
We don't currently expose all pairs from our production system on the sandbox

**Comment by ghost** [comment]
Why is that?

How can we test new API if it is that much limited?

**Comment by cyip** [comment]
api-sandbox is just a preview of what OANDA may offer in the future, and we limit what we support on sandbox.  At this moment, we don't recommend users using api-sandbox to test any system or algorithm they he/she may wish deploy on live trading environment.
