### ISSUE TITLE
Streaming rates instrument naming conventions

### ISSUE THREAD

**Issue by ccbcraig** [oanda/apidocs#23]
Streaming rates is great! However it currently seems to use instrument display names rather than the instrument names returned by /v1/instruments. Maybe it (and other parts of the API) could accept "EUR_USD" as well as "EUR/USD", for example.

**Comment by ghost** [comment]
Please add Heartbeat messages to your streaming rates solution. Like it was implemented in compact tick protocol.

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
