### ISSUE TITLE
Update documentation to correctly reflect recent changes to account creation

### ISSUE THREAD

**Issue by cloudspider** [oanda/apidocs#24]
The Create a Test User section in Getting started is no longer valid.

The /users api has been removed and the following link to create an account no longer works.
http://developer.oanda.com/gen-account.html

The following pages need to be updated.

https://github.com/oanda/apidocs/blob/master/sections/getting_started.md
https://github.com/oanda/apidocs/blob/master/sections/trading_quick_start.md

**Comment by cyip** [comment]
This has been fixed
