### ISSUE TITLE
Account creation returns a 502 Bad Gateway error

### ISSUE THREAD

**Issue by cloudspider** [oanda/apidocs#25]
Creating a new account via
   POST  http://api-sandbox.oanda.com/v1/accounts

Returns a 502 Bad Gateway error.

Test using:
https://apigee.com/oandapoc/embed/console/oanda?req=%7B%22resource%22%3A%22accounts%22%2C%22params%22%3A%7B%22query%22%3A%7B%7D%2C%22template%22%3A%7B%7D%2C%22headers%22%3A%7B%7D%2C%22body%22%3A%7B%22attachmentParamName%22%3A%22file%20attachment%22%2C%22attachmentFormat%22%3A%22mime%22%2C%22attachmentContentDisposition%22%3A%22form-data%22%7D%7D%2C%22verb%22%3A%22post%22%7D

Also, the new method of creating an account does not allow the ability to set the currency The Account controller no longer has a Currency parameter as there was previously with:

-#### Request
-    curl -X POST -d 'currency=AUD' http://api-sandbox.oanda.com/v1/users

**Comment by cyip** [comment]
POST /v1/accounts now supports currency
