### ISSUE TITLE
Socket.io javascript source is not available

### ISSUE THREAD

**Issue by jongillham** [oanda/apidocs#26]
http://api-sandbox.oanda.com/ratestream/socket.io.js returns a 404 error.

**Comment by cyip** [comment]
We have taken out support for the streaming API on the sandbox for now.

**Comment by ghost** [comment]
Why is that?

Will it be supported in the production-ready API ?

**Comment by cyip** [comment]
Rate streaming API is still in experimental stage.  We are not sure if it will be in our API when we launch initially, but it is definitely something we are considering adding to our API.

**Comment by ghost** [comment]
API without streaming rates would be a major failure. Don't do this.
