### ISSUE TITLE
Not returning anything when two trade Ids are specified.

### ISSUE THREAD

**Issue by JeKim** [oanda/apidocs#29]
When http://api-sandbox.oanda.com/v1/accounts/1179804/trades?count=4&instrument=EUR_USD&tradeId=176201454,176201356 url is request, it should return two trades but it's not returning anything.

**Comment by gershbn** [comment]
Comma should be url encoded.
http://api-sandbox.oanda.com/v1/accounts/1179804/trades?count=4&instrument=EUR_USD&tradeIds=176201454%2C176201356

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
