### ISSUE TITLE
When requesting for account open trades, the "nexPage" key should have an empty value when there are no unique trades on the next page

### ISSUE THREAD

**Issue by Davidkle** [oanda/apidocs#30]
http://api-sandbox.oanda.com/v1/accounts/1179804/trades?count=50&instrument=EUR_USD&maxTradeId=176201355&tradeIds=176201356

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
