### ISSUE TITLE
Inconsistent names for transaction ids

### ISSUE THREAD

**Issue by Davidkle** [oanda/apidocs#31]
Please make the keys for the transactions ids the same. Currently the response from opening a trade is "opened" and 'id" for modifying and closing a trade. Instead, change everything to "transactionId".

This is the response when a trade is opened
      {
        closed = ();
        instrument = "EUR_USD";
        interest =();
        marginUsed = "6.11";
        opened = 176203144;
        price = "1.2598";
        side = buy;
        time = "2013-05-28T15:59:18Z";
        units = 97;
        updated = 0;
    }

This is the response when a trade is modified
        {
        id = 176203144;
        instrument = "EUR_USD";
        price = "1.2598";
        side = buy;
        stopLoss = 0;
        takeProfit = 0;
        time = "2013-05-28T15:59:18Z";
        trailingStop = 0;
        units = 97;
    }

This is the response when a trade is closed
        {
        id = 176203144;
        instrument = "EUR_USD";
        price = "1.2598";
        side = buy;
        stopLoss = 0;
        takeProfit = 0;
        time = "2013-05-28T15:59:18Z";
        trailingStop = 0;
        units = 97;
    }

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
