### ISSUE TITLE
Creating more that 26 open trades is not permitted

### ISSUE THREAD

**Issue by mcotoole** [oanda/apidocs#34]
If there are 26 open trades any additional attempts to open another trade generates a 403 error:
 HTTP error code : 403 Msg: Forbidden Request

This trading limit is not present on the current Oanda API.

**Comment by Panurgo** [comment]
I think we should understand that rest api is in sandbox mode, so there are a lot of limitations. There is a rate request limit, authentication is turned off and even instrument price is nor real.
We should wait the api to be ready for fx practice accounts to test its limits.

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
