### ISSUE TITLE
Price data not accurate in the sandbox?

### ISSUE THREAD

**Issue by hellopatrick** [oanda/apidocs#35]
If you visit http://api-sandbox.oanda.com/v1/instruments/EUR_USD/price right now, it returns:

```
{
    "instrument": "EUR_USD",
    "time": 1371124431.220175,
    "bid": 1.25971,
    "ask": 1.2598
}
```

However, the current spot rate is definitely not that. It is around ~1.332 currently.

**Comment by webpolis** [comment]
Right.. all pairs have an average difference +13% against other sources (etoro, yahoo, etc)

**Comment by ghost** [comment]
If you need to access real rates use **practice** or **live** environment. Sandbox provides generated (fake) market data. See: http://developer.oanda.com/docs/v1/guide/

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
