### ISSUE TITLE
Link on README.md does not work

### ISSUE THREAD

**Issue by ptav** [oanda/apidocs#46]
Clicking on http://api-sandbox.oanda.com/v1/quote?instruments=EUR_USD, returns 

{
    "code" : 38,
    "message" : "No matching handler for the request is found",
    "moreInfo" : "http:\/\/developer.oanda.com\/docs\/v1\/troubleshooting\/#errors"
}

**Comment by jmunnings** [comment]
This document is out-of-date, please refer to developer.oanda.com for any REST API documentation.

**Comment by abendigo** [comment]
Could we update this readme to point to the new docs?
