### ISSUE TITLE
quoteHomeConversionFactors Deprecated

### ISSUE THREAD

**Issue by lgimyuen** [oanda/apidocs#47]
In V20 REST API, quoteHomeConversionFactors  is an important figure for trader to decide how many unit to trade in their account currency. I hope this will not be deprecated. 

source: http://developer.oanda.com/rest-live-v20/pricing-df/#Price

**Comment by dmpettyp** [comment]
We plan on hoisting these conversion factors out of the Price object and place them in the response along side the Prices. They won't be going away, but they will appear in a different place in the response. Having them embedded in the Price object often results in a lot of duplicate data found in the response.

**Comment by lgimyuen** [comment]
I see, great to hear that it won't go away. Thanks!
