### ISSUE TITLE
Transaction history needs time based retrieval

### ISSUE THREAD

**Issue by ccbcraig** [oanda/apidocs#7]
This may be an oversight but time based retrieval is supported by the website but not here. While minTransId and maxTransId are useful for pagination most operations on transaction history are based on time - today, yesterday, last week, this week, etc. The proposed implementation without minTime and maxTime requires a developer to maintain a local database of transaction history for typical analyses and is not much use for ad hoc queries.

**Comment by abendigo** [comment]
closing this issue as these docs are for the old api. If there are any new issues, please raise them in the v20 api docs.
